# Generated by Django 3.1.7 on 2021-08-14 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_rank', models.CharField(max_length=150)),
                ('role', models.CharField(max_length=150)),
                ('employees', models.CharField(max_length=150)),
                ('added_time', models.DateField()),
            ],
        ),
    ]
