# Generated by Django 3.1.7 on 2021-06-21 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPattern',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_pattern', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Group Pattern',
                'verbose_name_plural': 'Group Pattern',
            },
        ),
    ]
