# Generated by Django 3.1.7 on 2021-06-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20210626_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgroup',
            name='first_lesson',
            field=models.DateField(),
        ),
    ]
