# Generated by Django 3.1.7 on 2021-06-26 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0006_auto_20210626_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgroup',
            name='lesson_time',
            field=models.CharField(max_length=255),
        ),
    ]
