# Generated by Django 3.2.4 on 2021-06-09 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_types', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lesson type',
                'verbose_name_plural': 'Lesson Types',
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Lesson Pattern',
                'verbose_name_plural': 'Lesson Patterns',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateField()),
                ('finish_time', models.DateField()),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='settings.group')),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_patterns', to='settings.patterns')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='settings.lessontype')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='settings.subjects')),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetable',
            },
        ),
    ]
