# Generated by Django 3.1.7 on 2021-06-21 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('room_amount', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=255)),
                ('added_time', models.DateField()),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_type', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_types', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lesson type',
                'verbose_name_plural': 'Lesson Types',
            },
        ),
        migrations.CreateModel(
            name='Patterns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patterns', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Lesson Pattern',
                'verbose_name_plural': 'Lesson Patterns',
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Room type',
                'verbose_name_plural': 'Room types',
            },
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='TeacherRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Teacher Role',
                'verbose_name_plural': 'Teacher Role',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_types', to='settings.group')),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_patterns', to='settings.patterns')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='settings.lessontype')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_name', to='settings.subjects')),
            ],
            options={
                'verbose_name': 'timetable',
                'verbose_name_plural': 'timetable',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('id_code', models.CharField(max_length=20)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('born_date', models.DateField()),
                ('student_age', models.IntegerField()),
                ('document_type', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=20)),
                ('id_card_number', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=20)),
                ('free_time', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('tel_number', models.CharField(max_length=20)),
                ('student_login', models.CharField(max_length=150)),
                ('student_password', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=20)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_building', to='settings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('id_code', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=25)),
                ('register_date', models.DateField()),
                ('born_date', models.DateField()),
                ('document_type', models.CharField(max_length=250)),
                ('passport_id', models.CharField(max_length=250)),
                ('id_card_number', models.CharField(max_length=25)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_role', to='settings.teacherrole')),
                ('workplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workplace', to='settings.building')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amount', models.IntegerField()),
                ('monthly_fee', models.IntegerField()),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_group_types', to='settings.group')),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lesson_patterns', to='settings.patterns')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lessons', to='settings.lessontype')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_subject_name', to='settings.subjects')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=100)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='settings.building')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_type', to='settings.roomtype')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_plan', models.IntegerField()),
                ('monthly_plan', models.IntegerField()),
                ('total_lessons', models.IntegerField()),
                ('course_duration', models.IntegerField()),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lesson_patterns', to='settings.patterns')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subject_name', to='settings.subjects')),
            ],
        ),
    ]
