# Generated by Django 3.2.4 on 2021-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='finish_time',
            field=models.TimeField(default='20:00'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(default='20:00'),
        ),
    ]
