# Generated by Django 3.1.7 on 2021-06-14 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('settings', '0002_auto_20210609_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('room_amount', models.IntegerField(default=0)),
                ('nickname', models.CharField(max_length=255)),
                ('added_time', models.DateField()),
            ],
            options={
                'verbose_name': 'building',
                'verbose_name_plural': 'buildings',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('middle_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('id_code', models.CharField(max_length=250)),
                ('gender', models.CharField(max_length=25)),
                ('register_date', models.DateField()),
                ('born_date', models.DateField()),
                ('document_type', models.CharField(max_length=250)),
                ('passport_id', models.CharField(max_length=250)),
                ('id_card_number', models.CharField(max_length=25)),
                ('role', models.CharField(max_length=250)),
                ('workplace', models.CharField(max_length=250)),
                ('login', models.CharField(max_length=250)),
                ('password', models.CharField(max_length=250)),
            ],
            options={
                'verbose_name': 'staff',
                'verbose_name_plural': 'staff',
            },
        ),
        migrations.RemoveField(
            model_name='group',
            name='active',
        ),
        migrations.RemoveField(
            model_name='lessontype',
            name='active',
        ),
        migrations.RemoveField(
            model_name='patterns',
            name='active',
        ),
        migrations.RemoveField(
            model_name='subjects',
            name='active',
        ),
        migrations.AlterField(
            model_name='group',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lessontype',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='patterns',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='finish_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('middle_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('id_code', models.CharField(max_length=20)),
                ('register_date', models.DateField(auto_now_add=True)),
                ('born_date', models.DateField()),
                ('student_age', models.IntegerField()),
                ('document_type', models.CharField(max_length=150)),
                ('id_number', models.CharField(max_length=20)),
                ('id_card_number', models.CharField(max_length=25)),
                ('level', models.CharField(max_length=20)),
                ('free_time', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('tel_number', models.CharField(max_length=20)),
                ('student_login', models.CharField(max_length=150)),
                ('student_password', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=True)),
                ('gender', models.CharField(max_length=20)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_building', to='settings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_amount', models.IntegerField()),
                ('monthly_fee', models.IntegerField()),
                ('group_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_group_types', to='settings.group')),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lesson_patterns', to='settings.patterns')),
                ('lesson_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_lessons', to='settings.lessontype')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_subject_name', to='settings.subjects')),
            ],
            options={
                'verbose_name': 'salary',
                'verbose_name_plural': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=30)),
                ('room_type', models.CharField(max_length=30)),
                ('owner', models.CharField(max_length=100)),
                ('building_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_name', to='settings.building')),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_plan', models.IntegerField()),
                ('monthly_plan', models.IntegerField()),
                ('total_lessons', models.IntegerField()),
                ('course_duration', models.IntegerField()),
                ('lesson_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_lesson_patterns', to='settings.patterns')),
                ('subject_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_subject_name', to='settings.subjects')),
            ],
        ),
    ]
