# Generated by Django 3.1.7 on 2021-08-14 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Teacher',
            new_name='TeacherTypes',
        ),
        migrations.AlterModelOptions(
            name='teachertypes',
            options={'verbose_name': 'Teacher type', 'verbose_name_plural': 'Teacher types'},
        ),
    ]
