# Generated by Django 3.1.7 on 2021-06-26 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0005_auto_20210626_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newgroup',
            name='first_lesson',
            field=models.DateField(blank=True, null=True),
        ),
    ]
